services:
  ecs:
    networks:
      - challenge
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile
    command: [ "bun", "run", "start:dev", "ecs-worker" ]
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_PROXY=${OPENAI_PROXY}
      - YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
      - YOOKASSA_RETURN_URL=${YOOKASSA_RETURN_URL}
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
      - COCKROACH_HOST=${COCKROACH_HOST}
      - COCKROACH_PORT=${COCKROACH_PORT}
      - COCKROACH_USER=${COCKROACH_USER}
      - COCKROACH_PASSWORD=${COCKROACH_PASSWORD}
      - COCKROACH_DATABASE=${COCKROACH_DATABASE}
      - REDIS_HOST=dragonfly
      - REDIS_PORT=6379
      - PORT=3000
      - NODE_OPTIONS=--max-old-space-size=4096
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=LZao1JfHY5Rw
      - WEB_APP_URL=${WEB_APP_URL}
      - WEB_APP_HOST=${WEB_APP_HOST}
      - NODE_ENV=development
    depends_on:
      - dragonfly
      - cockroachdb
    volumes:
      - ./app/apps:/app/apps
      - ./app/migrations:/app/migrations
    healthcheck:
      test: curl -f http://localhost:3000/api/health || exit 1
      interval: 1s      # how often to run
      timeout: 1s        # kill the curl if it hangs
      retries: 3         # consecutive failures before UNHEALTHY
      start_period: 10s  # grace period after container starts
    labels:
      autoheal: "true"
  telegram:
    networks:
      - challenge
    extends:
      service: ecs
    command: [ "bun", "run", "start:dev", "telegram" ]
  moderation:
    networks:
      - challenge
    extends:
      service: ecs
    command: [ "bun", "run", "start:dev", "moderation" ]
  dragonfly:
    networks:
      - challenge
    restart: always

    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    command: [ "--default_lua_flags=allow-undeclared-keys" ]
    ports:
      - "6379:6379"
    volumes:
      - dragonflydata:/data
    labels:
      autoheal: "true"
  cockroachdb:
    networks:
      - challenge
    image: cockroachdb/cockroach:v25.2.0 # From CockroachDB docs [1]
    container_name: ${COCKROACH_HOST}
    restart: always
    ports:
      - "26258:26257"
    volumes:
      - cockroach_data:/cockroach/cockroach-data # Persists data [1]
    command: start-single-node --insecure
    environment:
      - COCKROACH_USER=${COCKROACH_USER}
      - COCKROACH_PASSWORD=${COCKROACH_PASSWORD}
      - COCKROACH_DATABASE=${COCKROACH_DATABASE}
      - ZONEINFO=UTC
    healthcheck:
      test: cockroach sql  -e "SELECT uuid from public.users limit 1;" --insecure -d public || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 45s
    labels:
      autoheal: "true"

  nats:
    image: nats
    restart: always
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks:
      - challenge
  nats-1:
    image: nats
    restart: always
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - challenge
    depends_on: [ "nats" ]
  nats-2:
    image: nats
    restart: always
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - challenge
    depends_on: [ "nats" ]

  analytics-sink:
    networks:
      - challenge
    extends:
      service: ecs
    command: [ "bun", "run", "start:dev", "analytics-sink" ]
  clickhouse:
    networks:
      - challenge
    restart: always
    image: clickhouse/clickhouse-server
    user: "101:101"
    ports:
      - "8321:8123"
    hostname: clickhouse
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./clickhouse/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
    labels:
      autoheal: "true"

volumes:
  dragonflydata:
  cockroach_data:
  clickhouse_data:

networks:
  challenge:


