FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml setup.cfg /app/
RUN pip install --upgrade pip \
    && pip install -e ".[test]"

COPY . /app

CMD ["pytest"]
